export type ArticulationIconId =
  | 'notehead-x'
  | 'notehead-circle-open'
  | 'notehead-plus'
  | 'notehead-diamond'
  | 'notehead-triangle'
  | 'notehead-circle'
  | 'notehead-circle-ghost'
  | 'notehead-cross'
  | 'notehead-buzz'
  | 'notehead-flam'
  | 'notehead-drag'
  | 'notehead-circle-x'
  | 'sticking-r'
  | 'sticking-l'
  | 'sticking-both'
  | 'sticking-count'
